### ISSUE TITLE
It looks like KillSwitch is disabled by default.  Is there any way to enable it?

### ISSUE THREAD

**Issue by jensenkd** [nrdvpn/client#2]
2021/10/22 06:28:36 Technology set to: NORDLYNX
NordVPN App Connection Settings:
Technology: NORDLYNX
Protocol: UDP
Firewall: enabled
KillSwitch: disabled
Obfuscate: disabled
Notify: disabled
Auto-connect: disabled

2021/10/22 06:28:36 OK
Technology is successfully set to 'NORDLYNX'.
Subnet 172.18.0.0/16 is whitelisted successfully.
Subnet 192.168.10.0/23 is whitelisted successfully.

**Comment by bubuntux** [comment]
it doesnt matter, a kill switch is provided using iptaples
